### ISSUE TITLE
Crossing the Rubicon quirk doesn't let you walk over sewer catwalks.

### ISSUE THREAD

**Issue by IHaveNoOriginality** [WorldOfDarknessXIII/World-of-Darkness-13#321]
Reporting client version: 515.1647

## Round ID:
[500](https://scrubby.melonmesa.com/round/500)

## Reproduction:
Enter the sewers with the Crossing the Rubicon quirk, try to cross a catwalk bridge.

**Comment by Pluvifera** [comment]
that's.. kinda why this is a flaw. Can't cross over running water or the likes of which might be a similar experience.

**Comment by Pluvifera** [comment]
Intended.
